version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: traffic-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: trafficdb
      MYSQL_USER:      traffic_user
      MYSQL_PASSWORD:  traffic_pass
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
