apiVersion: v1
kind: Service
metadata:
  name: anomaly-detection-svc
  namespace: thefellows-namespace
spec:
  selector:
    app: anomaly-detection
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9097
  type: ClusterIP
