apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-simulator
  namespace: thefellows-namespace
  labels:
    app: traffic-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic-simulator
  template:
    metadata:
      labels:
        app: traffic-simulator
    spec:
      containers:
        - name: traffic-simulator
          image: traffic-simulator:latest
          ports:
            - containerPort: 9091
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
