apiVersion: v1
kind: Service
metadata:
  name: uiandrest-svc
  namespace: thefellows-namespace
spec:
  selector:
    app: uiandrest
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9095
      nodePort: 31095
  type: NodePort
